<a href="https://colab.research.google.com/github/GhanshamSoomarani/Data-Science-Analytics/blob/main/20sw081(Lab_4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Lab 4**

Task 1

In [11]:
import numpy as np

X = np.arange(2, 33, 2).reshape(4, 4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


Task 2

In [12]:
import numpy as np

X = np.arange(1, 26).reshape(5, 5)

Y = X[X % 2 != 0]

print("Original Array:")
print(X)
print("\nArray with Odd Numbers:")
print(Y)

Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array with Odd Numbers:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


Task 3

In [13]:
import numpy as np

X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


Task 4

In [14]:
from google.colab import drive
drive.mount('/NumPy.ipynb')
import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)

# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

Drive already mounted at /NumPy.ipynb; to attempt to forcibly remount, call drive.mount("/NumPy.ipynb", force_remount=True).
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[-0.1009824   1.26317794  1.49025872 ... -0.81694063 -0.02691945
   1.03406355]
 [ 0.32396808 -0.078307    0.13439259 ...  1.35326912  1.73004814
   1.69914252]
 [ 1.34250018 -1.09415621 -0.24972317 ...  0.64902428  0.63229255
   0.51012452]
 ...
 [-0.83823776  1.37933254 -0.19415489 ... -0.49840314 -0.88026381
   1.18690778]
 [-1.17077837  0.56826457  1.54165939 ... -1.01983516 -0.97314007
  -1.31574446]
 [ 0.86561131  0.84824416 -0.53728904 ... -0.5960418   1.75239431
   0.76211097]]
Average of all values in X_norm: 2.9842794901924206e-17
Average of minimum values in each column of X_norm: -1.7199901889193037
Average of maximum values in each column of X_norm: 1.7205430116959757
Random permutation of row indices: [ 90 155 240 919 135 840  78 890 900 108 923 338 197 499 315  77 459 